/*
 * Copyright 2023 New Relic Corporation. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

const CSEC_CALCULATING_APPLICATION_SHA = 'CSEC_CALCULATING_APPLICATION_SHA';
const CSEC_TASK_PAYLOAD_IDENTIFIER = 'CSEC_TASK_PAYLOAD';

module.exports = {
    CSEC_TASK_PAYLOAD_IDENTIFIER,
    CSEC_CALCULATING_APPLICATION_SHA
};
